### PR TITLE
Mccalluc/port celldive pr

### LINKED ISSUE #2: Apply Cell DIVE PR here
- Apply https://github.com/hubmapconsortium/portal-ui/pull/2279 to this repo

### PR DESCRIPTION
**Pull request by mccalluc**
- replace https://github.com/hubmapconsortium/portal-ui/pull/2279
- fix #2

@ilan-gold : A few changes needed to be made along the way, but the only necessary change to the test fixture was the addition of a metadata section, I think because the old test framework skipped the step that determined which builder to use.

I really don't know the bigger picture / what needs to be checked to say this is good.

### CODE REVIEW

**Comment by ilan-gold** [comment]
We won't be merging this for a little bit anyway so it's no biggy.  I can merge once ready.

**Comment by mccalluc** [comment]
@ilan-gold : Sorry: I hadn't realized this wasn't complete. I'll change it to draft to remind me that it's not ready to go, and I'll consider it to be in your court from here. Thanks!

**Comment by mccalluc** [comment]
Update from Joel:
> I believe https://portal.dev.hubmapconsortium.org/browse/dataset/48f0a5ae6fa636266df3dff4cd1033aa is a fully-up-to-date CellDIVE dataset. Ilan Gold has that path. We spent a long time getting the examples straightened out yesterday. This testing is being done on DEV to make it quicker to change things like vitessce-hints for the assay types.

**Comment by mccalluc** [comment]
Pinned my local portal instance to this version and looked at http://localhost:5001/browse/dataset/48f0a5ae6fa636266df3dff4cd1033aa on the DEV instance, and it looks reasonable.

**Review by ilan-gold — APPROVED** [review]
I've tested this with all the relevant datasets (old codex directory structure for stitched and unstitched, new codex directory strucutre, and cell dive).  I've also done some testing on PROD with current CODEX.  Everything seems to work.

**Comment by mccalluc** [comment]
After merging this the build is broken... This PR started a while ago, and then a lot of test infrastructure was added... but the last merge from master should have errored if there was a problem... So I'm somewhat confused. Filed #22 / working on it.

**Pull request merged**
