### PR TITLE
Mccalluc/init

### PR DESCRIPTION
**Pull request by mccalluc**
- copy over content from portal-ui
- reorganize directory structure to separate code and tests

Looking ahead:
- Prepare a PR for portal-ui that incorporates this code as a submodule
- Prepare a PR for search-api that incorporates this code at index-time
- Follow-up with portal-ui and use precomputed view-conf by default... but keep the submodule around for development.

### CODE REVIEW

**Comment by ilan-gold** [comment]
Just to be clear, view configurations would now be in the elasticsearch index?

**Comment by jswelling** [comment]
Under the proposal as I understand it, view configurations would be in the dataset JSON available from entity-api but not in the search index.  It could get copied to the search index, but I understand there is already an uncomfortable amount of data in there?

**Comment by mccalluc** [comment]
@jswelling :
> view configurations would be in the dataset JSON available from entity-api but not in the search index

No: This would be more information in the Entity JSON in the search index.
- We already have a mechanism for adding information to the search index: We would just add this to that.
- Portal index only adds information to the raw JSON provided by entity-api: There is no plan to have some information in the entity-api JSON but not in the search index.
- The ES limits that have been raised repeatedly relate to the number of indexed fields. Instead of just upping the limit, IEC could distinguish between stored-only and stored-and-indexed fields. It's up to them.

**Review by ilan-gold — APPROVED** [review]
This looks ok to me.  The only thing is https://github.com/hubmapconsortium/portal-ui/pull/2279 but I can migrate it here once I have the chance.

**Comment by mccalluc** [comment]
@ilan-gold : Thanks! I'll handle the migration -- It should be pretty mechanical, so I should be able to handle it. Thanks, though.

> This looks ok to me. The only thing is hubmapconsortium/portal-ui#2279 but I can migrate it here once I have the chance.

**Pull request merged**
