### PR TITLE
(feat): support new annotations

### LINKED ISSUE #74: (feat): support new annotations
There are new annotation columns coming from the CWL azimuth workflow and we need to support them. See https://hubmapconsortium.slack.com/archives/C02HKB41YGG/p1678472388823659

### PR DESCRIPTION
**Pull request by ilan-gold**
Fixes #74

### CODE REVIEW

**Comment by ilan-gold** [comment]
In the interest of not letting this get out of hand, I pinned vitessce since it's pinned in the portal anyway. c'est la vie.

**Comment by ilan-gold** [comment]
also @keller-marknif you want to try, not sure what you want here @ngehlenborg but this also does not account for any spatial changes here

**Comment by john-conroy** [comment]
Once merged, I can make a new `portal-visualization` release and bump the portal/search-api.

**Comment by ilan-gold** [comment]
@john-conroy I think you are welcome to review, at least the outline and/or literal quality of the code.  The idea is as follows:

1. We open the backing zarr store
2. We check to see if the dataset is annotated (i.e., the `uns/...` key is present and has a True value) 
3. We then append the appropriate column to be visualizaed depending on what is present in `obs` - the new behavior should be present in 1c8bfe669dcdf2c4564f3a4a1403cd92 and the old behavior in any slide-seq dataset (i.e., 6b5d4d3a6af69a3bb82c4768cd24396c)
4. We make the column for the annotations wider if they are present and the dataset is not spatial

@ngehlenborg can correct me if i'm misssing something, but the code should reflect this.

**Comment by ilan-gold** [comment]
EDIT: updated which snRNA-seq should have the new behavior, apologies

**Review by john-conroy — APPROVED** [review]

**Pull request merged**
